### PR TITLE
Further theme refinements

### PR DESCRIPTION
**Pull request by paulrobertlloyd**
Last few major theme refinements:
- Make handles slightly smaller, add hover state
- Animate menu icon (doesn’t work quite right in Firefox however…)
- Review theme colours to ensure appropriate colour contrast
- Replace cool and warm palettes with greys based of accent colour
- Various other refinements.

### CODE REVIEW

**Comment by allmarkedup** [comment]
All looks good mate, and like the animated menu button! Merged in now, many thanks.

**Comment by paulrobertlloyd** [comment]
Thanks! Could you push an npm release with this change please?

**Comment by allmarkedup** [comment]
Ah yes forgot about that :-) just released v0.3.1 now.

**Comment by paulrobertlloyd** [comment]
Thanks. Have filed a bug for the Firefox close icon issue: https://github.com/frctl/mandelbrot/issues/13

**Pull request merged**
