### PR TITLE
Navigation search

### LINKED ISSUE #27: Add search functionality

### PR DESCRIPTION
**Pull request by ahebrank**
This is code from #74 refactored per https://github.com/frctl/mandelbrot/pull/74#issuecomment-462039108 to try to match existing component and styling rules. 

Additional changes include:

- use an updated `develop` base
- search all the `.Navigation ul` children, instead of just the first.

Ignore artifact `dist` files below.

Fixes #27

### CODE REVIEW

**Comment by ahebrank** [comment]
Updated patch-package patch: https://gist.github.com/ahebrank/3b47178322a9614f2931790b3cc2bd9e

**Comment by nqthqn** [comment]
Anything I can do to help move this along @ahebrank ? For now I will test

**Comment by LeBenLeBen** [comment]
@ahebrank Do you mind discarding the changes in the dist files so we can focus on the source?

**Comment by ahebrank** [comment]
Rerolled patch for 1.2.1: https://gist.github.com/ahebrank/52c19b3005748b89b04ff661e7168060

**Comment by nqthqn** [comment]
@jaasum this is the PR i was telling you about.

**Comment by akegan** [comment]
any updates on this PR?

**Comment by riten228** [comment]
Is there any update, if this PR is going to be merged?

**Comment by thomasaull** [comment]
I'm in a project which uses Fractal for a couple of weeks now and I miss a search function in the Web UI every day. Is this going to go anywhere?

**Comment by riten228** [comment]
@thomasaull , search can be added to project by overriding theme-overrides using similar logic, as it is present in PR.

**Comment by Konafets** [comment]
@riten228 Do you have some example code? I wondering if I have to copy `mandelbrot.js` into `theme-overrides` folder?

Currently I did this:

`fractal.js`
```js
// Mandelbrot theme customisation
const mandelbrot = require('@frctl/mandelbrot');

const myCustomTheme = mandelbrot({
  skin: 'fuchsia',
  panels: ['html', 'info', 'resources']
});

myCustomTheme.addLoadPath(__dirname + '/theme-overrides');

fractal.web.theme(myCustomTheme);
```

```
theme-overrides
├── assets
│   ├── js
│   │   ├── components
│   │   │   └── search.js
│   │   └── mandelbrot.js
│   └── scss
│       └── components
│           └── _search.scss
└── views
    └── partials
        └── navigation
            └── navigation.nunj
```

But no search is shown.

**Comment by aekong** [comment]
any update on this pr? it's 2020 baby! 🎉

**Comment by riten228** [comment]
> @riten228 Do you have some example code? I wondering if I have to copy `mandelbrot.js` into `theme-overrides` folder?
> 
> Currently I did this:
> 
> `fractal.js`
> 
> ```js
> // Mandelbrot theme customisation
> const mandelbrot = require('@frctl/mandelbrot');
> 
> const myCustomTheme = mandelbrot({
>   skin: 'fuchsia',
>   panels: ['html', 'info', 'resources']
> });
> 
> myCustomTheme.addLoadPath(__dirname + '/theme-overrides');
> 
> fractal.web.theme(myCustomTheme);
> ```
> 
> ```
> theme-overrides
> ├── assets
> │   ├── js
> │   │   ├── components
> │   │   │   └── search.js
> │   │   └── mandelbrot.js
> │   └── scss
> │       └── components
> │           └── _search.scss
> └── views
>     └── partials
>         └── navigation
>             └── navigation.nunj
> ```
> 
> But no search is shown.

@Konafets ,
Please add search.nunj file under navigation folder - folder structure needs to be same as it is mentioned in your reply.
Then, add the below code and you will have search shown in navigation panel - 
`const fractalThemeOptions = fractalTheme({
    nav: ['search', 'components', 'docs'],
      scripts: [
        'default',
        '/scripts/main.js'
      ],
      panels: [
        'notes', 'view', 'info', 'html', 'context', 'resources'
      ],
    "skin": theThemeColor
});`

and then load the theme - 
`/*
* Theme setup - tell Fractal to load path for theme overrides
*/
fractalThemeOptions.addLoadPath(`${fractalDir}/../<theme-overrides-location>`);
/*
* Theme setup - tell Fractal-build to use the configured theme by default
*/
fractal.web.theme(fractalThemeOptions);`

This PR has similar kind of changes.

**Comment by Konafets** [comment]
@riten228 

- There is no `search.nunj` in the PR. 
- How can I load the `search.js`?
- How do I load the `search.css`?

In the documentation I found `myCustomTheme.addLoadPath(__dirname + '/theme-overrides');`, this does not work. Fractal expects the path to the `views` folder here. I found this by calling
`console.log(myCustomisedTheme.loadPaths());` which gives:

```
[
  '~/Sites/website-renewal-frontend/theme-overrides',
  '~/Sites/website-renewal-frontend/node_modules/@frctl/mandelbrot/views' 
]
```

The whole chapter about Theme Customization https://fractal.build/guide/customisation/web-themes.html#template-customisation is incomplete and/or wrong.

Why is this PR not cleaned up, rebased and merged into the project? I don't get it.

**Comment by ahebrank** [comment]
For those looking to use this now, here's how we use this with the [patch](https://gist.github.com/ahebrank/52c19b3005748b89b04ff661e7168060) in https://github.com/frctl/mandelbrot/pull/81#issuecomment-483790523 using `patch-package` (https://www.npmjs.com/package/patch-package)

1. install patch-package: `npm i -g patch-package` (it may also work to install this as a dev-dependency)

2. add postinstall script in in package.json:

```
{
  <snip>
  "scripts": {
    "postinstall": "patch-package"
  },
  "dependencies": {
    "@frctl/fractal": "^1.2.0",
    "@frctl/mandelbrot": "1.2.1",
    <snip>
  }
}
```
3. place [patch](https://gist.github.com/ahebrank/52c19b3005748b89b04ff661e7168060) in directory `patches`
    ```
    mkdir patches && cd patches
    wget https://gist.githubusercontent.com/ahebrank/52c19b3005748b89b04ff661e7168060/raw/b2442201edc69d36d1a185c70c395a81c1204d3f/@frctl+mandelbrot+1.2.1.patch
    ```

4. `npm install`

**Review by mihkeleidast — APPROVED** [review]

**Comment by mihkeleidast** [comment]
I took the liberty to fix up this PR, improved the code style a bit & improved the behaviour a bit. Also fixed the tag search - now if you add some tags to your component (alternative names for components, for example), the search will take them into consideration.

**Pull request merged**
