### PR TITLE
Fix style for frctl/fractal#477

### PR DESCRIPTION
**Pull request by k-utsumi**
[This Fractal PR](https://github.com/frctl/fractal/pull/477) will break `<pre>`, so this PR will fix that.

### CODE REVIEW

**Comment by ryanbelisle** [comment]
Any eta on when this will be merged in?

**Comment by jwir3** [comment]
(Drive-by review) This all seems somewhat fine to me. The styling removes the hierarchical nature of `<code>` blocks within `<pre>` blocks for `.Prose` children, but I don't see that to be a problem.

**Comment by k-utsumi** [comment]
Umm...
image

~OK, I'll delete that.~
Rebased.

**Comment by LeBenLeBen** [comment]
@k-utsumi Thank you! I'll try to make a release happen in the following days.

**Comment by k-utsumi** [comment]
Thanks for responding 🙏

**Comment by k-utsumi** [comment]
still... 👀

**Comment by dutscher** [comment]
are there any plans for a new release?
cheers

**Comment by mihkeleidast** [comment]
We're working on it, but can't promise when that'll happen.

**Comment by k-utsumi** [comment]
`stale` closed same issue.
That bot doesn't work well in Fractal, so could you drop that?
https://github.com/frctl/fractal/issues/517

**Comment by k-utsumi** [comment]
I've launched this with Fractal. Thanks.
https://site-demo.karte.io/guidelines/index.html

**Pull request merged**
