### PR TITLE
Theme refinements

### PR DESCRIPTION
**Pull request by paulrobertlloyd**
This PR includes a number of refinements, mainly focused on spacing and typography (a second PR will be needed to review colour usage, especially across the different colour schemes).

Beyond visual adjustments, I’ve added JSHint and Stylelint configuration files (and include stylelint reporting in the CSS gulp task), ensured consistent property ordering, and fixed a few visual discrepancies that were appearing in Firefox. Thought I should stop here, before this PR gets any longer!

### CODE REVIEW

**Comment by paulrobertlloyd** [comment]
Oh, and I’ve also restyled the code/notes browser to make better use of screen real estate, and reinstated the tab icons. In doing so however, I noticed that clicking on the SVG icon will deselect the tab… not sure why.

**Comment by allmarkedup** [comment]
Thanks mate - this all looks good, although I've got to say I'm not a big fan of the little arrow toggles on the nav items being slammed right up against the edge of the window with no padding. Personal preference though so I'll merge it in and then we can argue about it later :-) I'll also fix the svg icon click issue.

Getting there!

**Comment by paulrobertlloyd** [comment]
Been arguing a little about this myself… though the icons could probably be moved closer to their labels, meaning they are not so tight to the edge. I can fix that in a subsequent PR.

Ultimately, I’m trying to make the most of available screen space… working on a laptop 24/7 gives you a greater appreciation of such things ;-)

**Comment by paulrobertlloyd** [comment]
You might also want to point @clagnut in the direction of the prose styles: proportional old style numerals for running text, tabular lining numerals for table cells. It’s the small things… (and Open Sans supports these  OpenType features, which is nice.)

**Comment by allmarkedup** [comment]
Yeah definitely up for trying to optimise screen space. Will merge it in shortly but I won't do a new release just yet as I've been making a few configuration style tweaks which need a simultaneous update of the web plugin. Should have everything tied up by the end of the day though.

**Pull request merged**
