### PR TITLE
Adds search

### PR DESCRIPTION
**Pull request by nqthqn**
Would this work? Ripped out of https://github.com/gtap-dev/nighthawk

### CODE REVIEW

**Comment by Dan9boi** [comment]
Looks very good to me!

**Comment by Dan9boi** [comment]
this fixes #27 btw...

**Comment by LeBenLeBen** [comment]
I gave it a quick look and beyond the fact that I would love to see this feature land and therefor appreciate the contribution, I cannot merge it as is.

There are a couple of issues that should be fixed first:
* Move inline styles to https://github.com/frctl/mandelbrot/blob/develop/assets/scss/components/_navigation.scss or a new component file depending on how you'll name your classes
* Move inline script to a dedicated JS file, probably in https://github.com/frctl/mandelbrot/tree/develop/assets/js/components
* Clean-up unused classes and rename the others to match the existing code base naming

Once it's clean, I'd be happy to put some more precise comments about the implementation.

**Comment by ahebrank** [comment]
I've got an update for this PR that's more in line with existing standards... but please merge #80 or something like it since as noted in #77 the node deps won't currently install.

https://github.com/ahebrank/mandelbrot/pull/1/files

If it's helpful for anyone in the meantime here's our [patch-package](https://www.npmjs.com/package/patch-package) patch: https://gist.githubusercontent.com/ahebrank/3b47178322a9614f2931790b3cc2bd9e/raw/77b30f434364182ab89923d6d407510525711129/@frctl+mandelbrot+1.2.0.patch

**Comment by LeBenLeBen** [comment]
Closing in favor of #81

**Pull request closed without merging**
