### PR TITLE
Add support for IE 11

### LINKED ISSUE #68: Panel Resizing Doesn't Work in IE11
The resize works with the navigation panel, but not with the two other resizable panels on the right side, e.g.:

2017-08-23 10_15_52-cart page_ default _ de sede frontend component library - internet explorer

What happens is that it marks the contents instead.

### PR DESCRIPTION
**Pull request by LeBenLeBen**
Fixes #68 #63 #56 #29

### CODE REVIEW

**Comment by Chapabu** [comment]
Do we need to fix the Symbol not defined error? Or did that one already get fixed...I can't remember :/

**Comment by allmarkedup** [comment]
@LeBenLeBen this looks great - just tested it and it's all working for me, excellent work :-)

**Comment by allmarkedup** [comment]
@Chapabu I'm not seeing the Symbol error so I guess it was fixed previously or this PR fixes it - possibly it was to do with the `for..of` loop that has now been swapped out?

**Comment by LeBenLeBen** [comment]
Yes the Symbol was the result of using for…of, its fixed by moving to for…in.

**Comment by Chapabu** [comment]
Great stuff :)

**Pull request merged**
